--1.  COMPUTE THE NUMBER OF DAYS REMAINING IN THIS YEAR...
SELECT DATEDIFF(
    MAKEDATE(YEAR(CURDATE()) + 1, 1),
    CURDATE()
    ) AS days_remaining;


--2.  FIND THE HIGHEST AND LOWEST SALARIES AND THE DIFFERENCE BETWEEN  OF THEM..

   SELECT
    MAX(sal) AS highest_salary,
    MIN(sal) AS lowest_salary,
    MAX(sal) - MIN(sal) AS difference
   FROM employee;

--3.  LIST EMPLOYEES WHOSE COMMISSION IS GREATER THAN 25% OF THEIR SALARIES...
           SELECT ename, sal, comm FROM employee
WHERE comm > sal * 0.25;

--4.  MAKE A QUERY THAT DISPLAYS SALARY IN THE DOLLAR FORMART...

         SELECT ename, CONCAT('$', sal) AS salary
             FROM employee;


--5. CREATE A MATRIX QUERY THAT DISPLAY THE JOB , THE SALARY FOR THAT JOB BASED ON DEPARTMENT NUMBER , AND THE TOTAL SALARY
--FOR THAT JOB FOR ALL DEPARTMENTS ,GIVING EACH COLUMN AN APPROPRIAYTE HEADING...
        SELECT  job,
    SUM(CASE WHEN deptno = 10 THEN sal ELSE 0 END) AS dept10,
    SUM(CASE WHEN deptno = 20 THEN sal ELSE 0 END) AS dept20,
    SUM(CASE WHEN deptno = 30 THEN sal ELSE 0 END) AS dept30,
    SUM(CASE WHEN deptno = 40 THEN sal ELSE 0 END) AS dept40,
    SUM(sal) AS total_salary
     FROM employee
GROUP BY job;


-- 6. QUERY THAT WILL DISPLAY THE TOTAL NUMBER OF EMPLOYEES ,AND OF THAT TOTAL THE NUMBER WHO WERE HIRED IN 1980,1981,1982 AND 1983.
--GIVE APPROPRIATE HEADING ...
SELECT COUNT(*) AS total_employees,
    SUM(CASE WHEN YEAR(hiredate)=1980 THEN 1 ELSE 0 END) AS y1980,
    SUM(CASE WHEN YEAR(hiredate)=1981 THEN 1 ELSE 0 END) AS y1981,
    SUM(CASE WHEN YEAR(hiredate)=1982 THEN 1 ELSE 0 END) AS y1982,
    SUM(CASE WHEN YEAR(hiredate)=1983 THEN 1 ELSE 0 END) AS y1983
 FROM employee;


-- 7. QUER TO GET THE LAST SUNDAY OF ANY MONTHS..

SELECT DATE_SUB(
    LAST_DAY('2026-02-01'),
    INTERVAL (DAYOFWEEK(LAST_DAY('2026-02-01')) - 1) DAY
) AS last_sunday;

-- 8. DISPLAY DEPARTMENT NUMBERS AND TOTAL  NUMBERS OF EMPLOYEES   WORKING IN EACH DEPARTMENT...

SELECT deptno, COUNT(*) AS total_employees
FROM employee
GROUP BY deptno;

-- 9. DISPLAY THE VARIOUS JOBS AND TOTAL NUMBERS OF EMPLOYEES WITHIN EACH JOB GROUP...

SELECT job, COUNT(*) AS total_employees
FROM employee
   GROUP BY job;

-- 10. DISPLAY THE DEPART NUMBERS AND TOTAL SALARY FOR EACH DEPARTMENT....
SELECT deptno, SUM(sal) AS total_salary FROM employee
    GROUP BY deptno;
